import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideMenu from "./components/SideMenu/SideMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-w-[1400px]`}
      >
        <div className="flex h-screen">
          <SideMenu />
          <main className="flex-1 bg-[#F5F5F5] p-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
